/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class annotool_select_mRMRNative */

#ifndef _Included_annotool_select_mRMRNative
#define _Included_annotool_select_mRMRNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     annotool_select_mRMRNative
 * Method:    miq
 * Signature: ([F[IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_annotool_select_mRMRNative_miq
  (JNIEnv *, jclass, jfloatArray, jintArray, jint, jint, jint);

/*
 * Class:     annotool_select_mRMRNative
 * Method:    mid
 * Signature: ([F[IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_annotool_select_mRMRNative_mid
  (JNIEnv *, jclass, jfloatArray, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
